name: Manual Inputs
on: workflow_dispatch

jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Version
        uses: actions/checkout@v3
        with:
          repository: prakash-cts/techtalk
          ref: version
          path: version
      - name: Checkout Version
        uses: actions/checkout@v3
        with:
          repository: prakash-cts/techtalk
          ref: master
          path: master
      - name: Update version
        run: |
          pwd
          ls
          cd version
          ls
          git branch
          cat version.txt
          cd ../master
          ls
  do-another-job:
    needs: bump-version
    name: Second job
    runs-on: ubuntu-latest
    steps:
      - name: Update version 2
        run: |
          pwd
          env
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
